@host = http://localhost:3000
@token = a541077f55714095bd5e36afe317d67be90b736301df804a9d045dd8d3b76fbb66768b5d3c48ebe4667b7558c2b84140

### CREATE DUMMY USER

GET {{host}}/auth

### REQUEST A TOKEN

POST {{host}}/auth/token
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

### REFRESH A TOKEN

PUT {{host}}/auth/refresh
Authorization: Bearer {{token}}

### INVALIDATE A TOKEN

DELETE {{host}}/auth/invalidate
Authorization: Bearer {{token}}

### EXCEPTION DISPLAY

GET {{host}}/example