@host = http://localhost:3000
@token = 704e3ad879734b6cb1d15f7129ac59777967a4321c8d8607b238aceb11a7784aaa784817faba807e822078df6108f231

### CREATE DUMMY USER

GET {{host}}/auth

### REQUEST A TOKEN

POST {{host}}/auth/token
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

### REFRESH A TOKEN

PUT {{host}}/auth/refresh
Authorization: Bearer {{token}}

### INVALIDATE A TOKEN

DELETE {{host}}/auth/invalidate
Authorization: Bearer {{token}}