@host = http://localhost:3000
@token = 71e5db44308d4b6fb469ea0759e34d52967a4dcd8beef310366f16e845ad1636378b26a106bc79d6615993ad65419c75

### CREATE DUMMY USER

GET {{host}}/auth

### REQUEST A TOKEN

POST {{host}}/auth/token
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

### REFRESH A TOKEN

PUT {{host}}/auth/refresh
Authorization: Bearer {{token}}

### INVALIDATE A TOKEN

DELETE {{host}}/auth/invalidate
Authorization: Bearer {{token}}